---
title: "Incidence of WDPA update on deforestation statistics in Madagascar"
author: "Florent Bédécarrats"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Abstract




```{js, eval=FALSE}
// WDPA monthly snapshots
var nov_24 = ee.FeatureCollection('WCMC/WDPA/202411/polygons');
var jan_25 = ee.FeatureCollection('WCMC/WDPA/202501/polygons');

// Keep only Madagascar
var mdgOnly = ee.Filter.stringContains('ISO3', 'MDG');
function clean(fc) {
  return fc.filter(mdgOnly); 
}

var nov_24_mdg = clean(nov_24);
var jan_25_mdg = clean(jan_25);


// Export
function exportGeoJSON(fc, name) {
  Export.table.toDrive({
    collection: fc,
    description: name,
    fileFormat: 'GeoJSON',
    folder: 'WDPA_exports'
  });
}

exportGeoJSON(nov_24_mdg, 'WDPA_Nov_2024_MDG');
exportGeoJSON(jan_25_mdg, 'WDPA_Jan_2025_MDG');

```

WDPA was updated in january 2025. We want to compare Oct. 2024 and July 2025. They have not undergone changes inbetween so the differences in fact concern Dec. 2024 to Jan. 2025.

```{r}
# Install if not present or old
if (!requireNamespace("mapme.biodiversity", quietly = TRUE) ||
    packageVersion("mapme.biodiversity") <= "0.9.4") {
  remotes::install_github("mapme-initiative/mapme.biodiversity",
                          upgrade = "never")
}  

# [1] "0.9.4"
library(tidyverse)
library(tmap)
library(sf)
library(wdpar)
library(mapme.biodiversity)
library(aws.s3)
library(geoarrow)
library(arrow)
library(progressr)
library(units)
library(future)
library(tictoc)

# Some parameters
dir.create("data", showWarnings = FALSE)
options(scipen = 999) # disable scientific notations

# Load files downloaded from GEE
save_object(bucket = "projet-betsaka", 
           object = "diffusion/wdpa_compare/gee_snapshots/WDPA_Nov_2024_MDG.geojson",
           file = "data/WDPA_Nov_2024_MDG.geojson",
           region = "")
save_object(bucket = "projet-betsaka", 
           object = "diffusion/wdpa_compare/gee_snapshots/WDPA_Jan_2025_MDG.geojson",
           file = "data/WDPA_Jan_2025_MDG.geojson",
           region = "")


# Read as sf
wdpa_2024 <- st_read("data/WDPA_Nov_2024_MDG.geojson") %>%
  mutate(version = 2024) 
wdpa_2025 <- st_read("data/WDPA_Jan_2025_MDG.geojson") %>%
  mutate(version = 2025) 

# Google earth engine created some geometry collections for a few PAs (7 in 2024)
# We convert them back to multipolygons
gc_to_multipolygon <- function(x) {
  if (st_geometry_type(x) == "GEOMETRYCOLLECTION") {
    polys <- st_collection_extract(x, "POLYGON")
    geom <- st_cast(st_combine(polys), "MULTIPOLYGON") 
    st_geometry(x) <- st_sfc(geom, crs = st_crs(x))
    return(x)
  } else {
    return(x)
  }
}

wdpa_2024 <- wdpa_2024 %>%
  split(seq_len(nrow(.))) %>%              
  map(gc_to_multipolygon) %>%              
  bind_rows()           

wdpa_2025 <- wdpa_2025 %>%
  split(seq_len(nrow(.))) %>%              
  map(gc_to_multipolygon) %>%              
  bind_rows()           


tmap_mode("view")
  tm_shape(wdpa_2024, name = "WDPA 2024 Nov") +
    tm_fill(fill = "blue", fill_alpha = 0.3) +
  tm_shape(wdpa_2025, name = "WDPA 2025 Jan") +
    tm_fill(fill = "red", fill_alpha = 0.3) 
```

We use the package mapme.biodiversity to compute the forest cover loss for each protected area. 

```{r}
wdpa_both <- wdpa_2024 %>%
  select(-GIS_M_AREA, -GIS_AREA) %>%
  rename(PARENT_ISO3 = PARENT_ISO) %>%
  bind_rows(wdpa_2025) %>%
  st_transform(4326) # WGS84

mapme_options(outdir = "/vsis3/projet-betsaka/diffusion/wdpa_compare/mapme")

with_progress({
  wdpa_both_mapme <- wdpa_both %>%
  get_resources(get_gfw_lossyear(), get_gfw_treecover())
})


plan(multisession, workers = 8)

tic("compute treecover area")
with_progress({
  wdpa_both_mapme <- wdpa_both_mapme %>%
  calc_indicators(calc_treecover_area(years = 2000:2024, min_cover = 30))
})
toc()
# compute treecover area: 191.18 sec elapsed
plan(sequential)

write_rds(wdpa_both_mapme, "data/wdpa_both_mapme.rds")
```


Compare

```{r}
wdpa_both_stats <- wdpa_both_mapme %>%
  mutate(area_ha = as.numeric(set_units(st_area(.), ha))) %>%
  select(WDPAID, version, assetid, area_ha, treecover_area) %>%
  portfolio_wide() %>%
  st_drop_geometry() %>%
  select(WDPAID, version, area_ha, 
         treecover_ha_2000 = `treecover_area_2000-01-01_treecover_ha`,
         treecover_ha_2024 = `treecover_area_2024-01-01_treecover_ha`) %>%
  mutate(total_defor_pct  = ((treecover_ha_2024 - treecover_ha_2000) / 
                               treecover_ha_2000) * 100) 


wdpa_both_wide <- wdpa_both_stats %>%
  mutate(version = paste0("v", version)) %>%
  pivot_wider(
    id_cols = WDPAID,
    names_from = version,
    values_from = c(area_ha, total_defor_pct),
    names_glue = "{.value}_{version}"
  ) %>%
  left_join(wdpa_2024 %>%
              st_drop_geometry() %>%
              select(WDPAID, NAME_2024 = NAME), 
            by = "WDPAID") %>%
  left_join(wdpa_2025 %>%
              st_drop_geometry() %>%
              select(WDPAID, NAME_2025 = NAME, STATUS_2025 = STATUS), 
            by = "WDPAID") %>%
  relocate(starts_with("NAME"), .after = WDPAID) %>%
  filter(STATUS_2025 == "Designated")


wdpa_both_wide <- wdpa_both_stats %>%
  mutate(version = paste0("v", version)) %>%
  pivot_wider(
    id_cols = WDPAID,
    names_from = version,
    values_from = c(area_ha, total_defor_pct),
    names_glue = "{.value}_{version}"
  ) %>%
  left_join(wdpa_2024 %>%
              st_drop_geometry() %>%
              select(WDPAID, NAME_2024 = NAME), 
            by = "WDPAID") %>%
  left_join(wdpa_2025 %>%
              st_drop_geometry() %>%
              select(WDPAID, NAME_2025 = NAME), 
            by = "WDPAID") %>%
  relocate(starts_with("NAME"), .after = WDPAID)

wdpa_diff <- wdpa_both_wide %>%
  mutate(area_ha_diff = 100*(area_ha_v2025 - area_ha_v2024) / area_ha_v2024,
         defor_pct_diff = 100*(total_defor_pct_v2025 - total_defor_pct_v2024) / 
           total_defor_pct_v2024)

write_parquet(wdpa_diff, 
              "s3://projet-betsaka/diffusion/wdpa_compare/wdpa_diff.parquet")
```


Compare

